apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-security-jwt
  labels:
    app: spring-boot-security-jwt
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-security-jwt
  template:
    metadata:
      labels:
        app: spring-boot-security-jwt
    spec:
      containers:
      - name: spring-boot-security-jwt
        image: spring-boot-security-jwt:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080